module.exports = async ({ modelName, types = [] }) => {
	const createModelDir = require('./createModelDir');
	const fs = require('fs');
	const dir = await createModelDir(modelName);
	const copyRight = '/**\n	This file was generated by API Client Genie\n*/\n\n';

	// generate types file
	fs.writeFile(dir + '/types.ts', copyRight + types.join('\n'), error => {
		console.log(error?.message);
	});
	// generate function file
	// generate index file
};
